test/CMakeLists.txt, test/src/unit-files.cpp
The tests fail if one uses another directory to build the tests, this is fixed here.
=> Change the file location to allow out-of-source builds

README.md, src/inja.hpp, test/src/unit-renderer.cpp, test/src/unit-string-helper.cpp
Adds an exists() function that checks whether a given key exists in the
data. If only one argument is provided to exists(), the global data is
queried for the item. If two arguments are given, the first argument
specifies the object to query for the key given as second argument.
Also adds corresponding unit tests and updates README for
documentation.
=> Add exists() function that checks existence of key

src/inja.hpp
https://stackoverflow.com/questions/16792456/no-matching-function-for-call-to-transform
This is a fix for using toupper and tolower with std::transform. Otherwise it can give an error because the function cannot be resolved properly.
=> Fix the std::transform bug

README.md, include/inja/config.hpp, single_include/inja/inja.hpp, test/unit-renderer.cpp
When updating the `opening_chars`, line_statment was forgotten. So, a
change to any of the openers would cause line statements to start being
unrecognized.
I added a unit test to cover this case.
=> Fix for issue #80

include/inja/renderer.hpp, single_include/inja/inja.hpp
I made the following changes in renderer.hpp
- Removed the member LoopLevel::it - it was not being used and was
causing issues.
- Added LoopLevel::loop_type with a matching enum class to mark the loop
as looping on either a Map or an Array. This was to replace the hard to
understand test for key_name.empty().
- Modified update_loop_data to get the correct data for map type loops
when copying in outer loop control data.
- Modified update_loop_data to only copy in the outer loop data during
StartLoop, it does not need to be done at EndLoop and can be expensive
since it can copy a large part of the json tree.
All the tests pass and the test cases from the issue also now work. Both
GCC and Clang will compile and run the tests with no issue. No issue is
seen with address_sanitizer in either …
=> Fix for issue #82 - Nested loops

include/inja/renderer.hpp, single_include/inja/inja.hpp, test/unit-renderer.cpp
Commit a5862a0 made the linking step in update_loop_data unecessary
because the loop's copy of the data was made to come from the parent
loop's data rather than the original client's data.
While at it, also add one more nested loop test case.
=> Remove unneed linking in update_loop_data

include/inja/parser.hpp, single_include/inja/inja.hpp
VS 2015 builds with error if include `inja` using C++11
```C++
#define nssv_CPLUSPLUS 201103L
#include <inja/inja.hpp>
```
Error log 
```
1>inja\include\inja\parser.hpp(267): error C2678: binary '==': no operator found which takes a left-hand operand of type 'nonstd::sv_lite::string_view' (or there is no acceptable conversion)
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\exception(329): note: could be 'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup]
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\exception(334): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup]
1>c:\program files (x86)\microsoft …
```
=> Fixed VS2015 error C2678: string_view to std::string comparison

CMakeLists.txt, requirements.txt
`nlohmann/json` has down graded the required version of CMake, this PR updates the version to ensure that `inja` can be build with a lower version of CMake.
=> update the version of nlohmann/json in requirements.txt

CMakeLists.txt, include/inja/environment.hpp, include/inja/parser.hpp, include/inja/utils.hpp, single_include/inja/inja.hpp, test/unit-files.cpp, test/unit-renderer.cpp
* Add a new function in utils.hpp: open_file_or_throw: This function
returns an opened std::ifstream or throws by calling `inja_throw`.
* Use this function in Parser::load_file which previously returned an
empty string if the file couldn't be opened.
* Use this function in Environment::load_json which previously threw
a `nlohmann::detail::parse_error` if the file couldn't be opened.
* In Parser::parse_statement: When including files through `include`,
do not attempt to (re-)parse templates from files that were already
included. Additionally, this prevents inja from attempting to load
in-memory templates by their name from disk.
* Add tests that check if an exception is thrown when attempting to
open files that do not exist.
If there is anything that I can do to get this merged, please let …
=> throw exception if a file cannot be opened, fix travis-ci builds

include/inja/config.hpp, include/inja/environment.hpp, include/inja/lexer.hpp
I add these options from Jinjas2 API.
When enabled together, they can give a nicer output to conditional and loop blocks, by eliminating whitespace on lines where these blocks reside alone.
https://tedboy.github.io/jinja2/templ6.html
It's implemented on comments and statements.
Compared against Jinjas2, I obtained identical outputs.
=> add whitespace control options: trim_blocks, lstrip_blocks

include/inja/renderer.hpp, single_include/inja/inja.hpp, test/unit-renderer.cpp
* Use data from current scope (m_data) when rendering an included template.
This allows included templates to access loop variables, which was not possible before.
* Add test
* This fixes issue #101.
* Commit 70096d42cd6a692a08e905bd7df72e7852f2dc83: The `single_include`-header was out of sync.
Example:
```
nlohmann::json data;
data["cities"] = nlohmann::json::array({{{"name", "Munich"}}, {{"name", "New York"}}});
data["locations"] = nlohmann::json::array({{{"name", "Amsterdam"}}, {{"name", "Mumbai"}}});
inja::Environment env;
env.include_template("item.tpl", env.parse("{{ loop.index1 }}: {{ item.name }}\n"));
env.render_to(
std::cout,
env.parse("{% for item in cities %}{% include \"item.tpl\" %}{% endfor %}"),
data);
env.render_to(
std::cout,
env.parse("{% for item in locations %}{% …
```
=> retain scope when including a template

include/inja/parser.hpp, single_include/inja/inja.hpp
Add a static cast to avoid `warning C4244: 'argument': conversion from 'unsigned __int64' to 'unsigned int', possible loss of data`. Introduced a new using typedef for this purpose.
=> Static cast to avoid VS140 C4244 warning

README.md
When using templates from an environment, `inja::env::render`
must be used.
Closes #121
=> Fix error in example for included templates

appveyor.yml
Hi,
I'd like to add more build configurations on Appveyor:
* Debug/Release
* x86/x64
* VS 2015/2017/2019
* C++ standard: 14/17
Currently VS 2015 and all Debug builds fail (you can see full status on this appveyor [job]( https://ci.appveyor.com/project/kzeslaf/inja/builds/28721345)) so I've commented these configurations out. I will try to fix them in additional pull requests.
Additionally I raised build output verbosity to see all build flags in appveyor build output, option: `-verbosity:n`.
=> Add more build configurations to appveyor

include/inja/environment.hpp, single_include/inja/inja.hpp, test/unit.cpp
* Environment now supports copy construction and assignment
* Add test for copying Environment
Closes #126
----
I am assuming the PIMPL pattern was left over from before inja became a header-only library. If I am missing something, please let me know.
=> Undo PIMPL pattern in Environment

appveyor.yml, include/inja/string_view.hpp, single_include/inja/inja.hpp
Hi,
* update string-view-lite to v1.4.0 (martinmoene/string-view-lite@88ad9b5, master, not released yet)
* generate inja-single-header (`./scripts/update_single_include.sh`)
=> Fix VS2015 build

CMakeLists.txt, appveyor.yml
Hi,
removing build flags `-DCMAKE_CXX_FLAGS="..."` from appveyor.yml file and moving them to CMakeLists.txt fixes Debug builds. Setting `CMAKE_CXX_FLAGS` on command line overrides default compile options set by cmake.
I've checked two builds (VS2017, C++17, x64) Debug and Release and now builds have following additional flags set:
```
/D WIN32 /D _WINDOWS /EHsc /GR
```
=> Fix Visual Studio Debug builds

include/inja/parser.hpp, include/inja/renderer.hpp, include/inja/utils.hpp, single_include/inja/inja.hpp
I encountered some warnings that can be easily fixed:
* One unused variable from a catch clause
* Multiple places where size_t should be used instead of int or unsigned int.
=> Fix warnings (VS2017 x64).

CMakeLists.txt
First, thanks for creating this awesome library!
Currently Inja's CMake config will build unit tests as long as the `BUILD_TESTING` option is enabled. As a result, when including Inja in another CMake project, it is not possible to build the latter's unit tests without also enabling Inja's own unit tests.
It's common for libraries to include a separate option for controlling its own unit test targets, in addition to observing the global `BUILD_TESTING` option. For instance, nlohmann/json has a `JSON_BuildTests` option: https://github.com/nlohmann/json/blob/973c52dd4a9e92ede5ca4afe8b3d01ef677dc57f/CMakeLists.txt#L18
Also see https://cliutils.gitlab.io/modern-cmake/chapters/testing.html .
This commit adds a `INJA_BUILD_TESTS` flag to address this.
=> Add CMake option to control Inja's unit tests.

requirements.txt, third_party/include/nlohmann/json.hpp
Update nlohmann/json to version 3.8.0.
I am working some other changes that require the new version.
Note: v3.8.0 fixes the MSVC compilation issues in v3.7.3
=> Move to json v3.8.0

include/inja/environment.hpp, include/inja/parser.hpp, include/inja/utils.hpp, single_include/inja/inja.hpp
There is an inline function that assumes the compiler has copy elision
optimization which is actually not required until C++17. GCC 4.8 does it
but it requires the copy constructor to be defined which is not the case
for std::ifstream. Fixed by passing reference by parameter.
=> Making it compatible with gcc 4.8

include/inja/renderer.hpp, single_include/inja/inja.hpp
This PR re-implements the exists() call by using `json->contains(json::json_pointer(JsonNode(name, 0).ptr));` instead of `json->find()`, which allows you to call `exists("array.1.name")` safely with no throw regardless of the existence of the array, the item in this array, or the `name` key in this item, so that you don't need to `exists("array")`, `existsIn("1", array)` and `existsIn("name", array.1)`.
=> Using another method for exists call

include/inja/parser.hpp, single_include/inja/inja.hpp, test/test-functions.cpp
#154 
Switching the order of function and operator behavior in the parser seems to fix the issue.
The occuring problem was that logic operators (or, and, not) were looked up as functions.
=> Switched order in token::kind::id of function and operator behavior

include/inja/config.hpp, include/inja/environment.hpp, include/inja/lexer.hpp, single_include/inja/inja.hpp
Implements whitespace control for expression like it said in #160. Should work as expected.
=> Add whitespace control for expression

include/inja/function_storage.hpp, single_include/inja/inja.hpp
Suppress `missing initializer for member 'inja::FunctionStorage::FunctionData::callback'` warnings by adding a constructor with empty default value to `callback`.
=> Suppress "missing initializer" warnings

CMakeLists.txt
This fixes https://github.com/pantor/inja/issues/175
The problem is that the `nlohmann/json.hpp` is included in the install directory even if the `INJA_USE_EMBEDDED_JSON` is set to `OFF`.
If `nlohmann/json.hpp` comes from another place (for example, a different version than the one in the `thid_party` folder), then you probably do not want to copy the embedded one it into the install directory.
This PR fixes that.
=> Do not install nlohmann json if it is not embedded

.github/workflows/ci.yml
This should fix the Ubuntu 20.04 CI failures.
Taken from an issue on the Docker for linux repo and a few other places:
https://github.com/docker/for-linux/issues/1131
Ubuntu bug report also seems to indicate this is safe:
https://bugs.launchpad.net/ubuntu-cdimage/+bug/1871268
=> Disabled immediate config on Linux CI libc6-dbg install

meson.build
Currently, the meson build is broken. This patch fixes it. 
It may be a good idea not to include source files but convert them to the header files.
=> Meson: Removing unneeded files from the config

include/inja/inja.hpp, include/inja/utils.hpp, single_include/inja/inja.hpp
If exceptions are disabled via `-fno-exceptions`, the use of try-catch is
disallowed by the compiler.
This patch does two things:
* Gates the use of try-catch in one translation unit on the definition of
`INJA_NOEXCEPTION`.
* Make it such that translation units compiled with `-fno-exceptions` but no
`INJA_NOEXCEPTION` implicitly sets `INJA_NOEXCEPTION`.
In the specific case of `ifstream::open`, setting the exceptions bits without
exceptions enabled should trip an assertion just like INJA_ABORT. The nice
message will not be present however, but that is absent when using INJA_ABORT as
well.
After this patch, inja can be successfully included without issue.
=> Fix inclusion in translation units with exceptions disabled.

.gitignore, include/inja/node.hpp, include/inja/renderer.hpp, single_include/inja/inja.hpp
Fix some build warnings for Clang and MSVC.
- unnecessary semicolons
- missing virtual desctructor
- implicit conversion from double to int
At the moment I have to disable some warnings when inja is included.
It would be nice if this is no longer needed.
```
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4244)
#else
#pragma clang diagnostic push
#pragma clang diagnostic warning "-Wextra-semi"
#pragma clang diagnostic warning "-Wnon-virtual-dtor"
#endif
#include <inja/inja.hpp>
#ifdef _MSC_VER
#pragma warning(pop)
#else
#pragma clang diagnostic pop
#endif
```
=> Fix build warnings for Clang and MSVC

LICENSE, README.md, include/inja/config.hpp, include/inja/environment.hpp, include/inja/exceptions.hpp, include/inja/function_storage.hpp, include/inja/inja.hpp, include/inja/lexer.hpp, include/inja/node.hpp, include/inja/parser.hpp, include/inja/renderer.hpp, include/inja/statistics.hpp, include/inja/template.hpp, include/inja/token.hpp, include/inja/utils.hpp, single_include/inja/inja.hpp, test/data/html-extend/base.txt, test/data/html-extend/data.json, test/data/html-extend/inter.txt, test/data/html-extend/result.txt, test/data/html-extend/template.txt, test/test-files.cpp
Add support for following [Jinja3 features](https://jinja.palletsprojects.com/en/3.0.x/templates/#template-inheritance):
- Block Statements.
- Extends Statements.
- Nested child inheritance.
- `super()` calls for rendering parent blocks.
=> Add Child Inheritance Feature

README.md, include/inja/renderer.hpp, include/inja/utils.hpp, single_include/inja/inja.hpp, test/test-renderer.cpp
This PR adds support for JSON pointers to set statements, e.g. `{% set x.y = 1 %}` sets the `y` member of `x` to 1.
Previously, you could use JSON pointer syntax in a set statement, but it did not work as you might expect. `{% set x.y = 1 %}` would render without errors, but `{{ x.y }}` would not be set to 1.
Tests are included. In addition to adding tests for set statements with JSON pointers, I also added tests for setting variables that are in the original JSON data, as such tests seemed to be missing.
I also updated the `README.md` section to explain that JSON pointers work to set sub-objects and that the set statement will not modify the underlying JSON object you pass in to a `render` call.
=> Add support for setting subobjects via JSON pointer in set statements.

README.md, include/inja/function_storage.hpp, include/inja/parser.hpp, include/inja/renderer.hpp, single_include/inja/inja.hpp, test/test-functions.cpp
Prototype join function (#199), what do you think?
Test and documentation not yet added.
This code
```
#include <iostream>
#include <vector>
#include <inja/inja.hpp>
int main()
{
auto data = nlohmann::json();
data["guests"] = std::vector{ "Jeff","Patrick","Tom" };
data["numbers"] = std::vector{ 1,2,3 };
std::cout << inja::render("{{ join(guests, \" - \") }}", data) << '\n';
std::cout << inja::render("{{ join(numbers, \" | \") }}", data) << '\n';
}
```
Generates this output
```
Jeff - Patrick - Tom
1 | 2 | 3
```
=> add join function

CMakeLists.txt
When using inja as a git submodule with a separate nlohmann_json subproject, CMake fails to configure it correctly because of this missing export.
=> Fixed exports for submodule builds with external nlohmann json parser.

include/inja/function_storage.hpp, include/inja/node.hpp, include/inja/parser.hpp, include/inja/renderer.hpp, single_include/inja/inja.hpp, test/test-functions.cpp
Close #246
This pull request consists of three commits.
1. The first commit adds the following method to `Parser` and use it in the `parse_expression` method with two arguments.
```c++
std::shared_ptr<ExpressionNode> parse_expression(Template& tmpl)
```
The method with one argument returns when unexpected token is found.
2. The second fixes #246. `parse_expression` with one argument is called recursively for each argument.
3. The third is optional. If you don't prefer it, I'll revert it. It calls `parse_expression` with one argument after a left parenthesis instead of counting the nested level by `current_paren_level`.
=> Fix issue 246

meson.build, meson_options.txt
This adds options to disable building the tests or benchmarks when using inja directly as a subproject in Meson.
By default, both tests and benchmarks will be built.
Changing the values can be done when importing the subproject like this:
inja_proj = subproject('inja', default_options: [
'build_benchmark=true',
'build_tests=false'
])
=> Add option to disable tests and benchmarks with Meson

README.md
=> c++17 support starts from gcc8

include/inja/lexer.hpp, single_include/inja/inja.hpp
Fixes the exception by switching
```cpp
if (ch == '\\') {
escape = true;
```
to
```cpp
if (ch == '\\') {
escape = !escape;
```
in `scan_string()`.
=> Fixes the json exception when using "\\" inside a string; closes #257

CMakeLists.txt
The exported cmake target does not find the embedded json library, because it looks in the wrong directory. It looks in `<prefix>/include/inja/json/include` but it is actually installed into `<prefix>/include/nlohmann`. This PR simply changes the directory where cmake looks to the actual install directory.
=> fix: cmake does not find embedded json

CMakeLists.txt
When including inja in another CMake project, it is desirable to set CMake options for the inja project in the containing project. This can be done through CMake variable setting. Unfortunately, for this to work correctly, both projects need to set [CMake policy 77](https://cmake.org/cmake/help/latest/policy/CMP0077.html) to `NEW`. This pull request sets this option in the inja project to allow for easier inclusion.
=> Set CMake policy 0077 for easy inclusion from other CMake prjs

include/inja/renderer.hpp, single_include/inja/inja.hpp, test/test-renderer.cpp
Values greater than the maximum positive value for int64_t do not render correctly -- they are rendered as negative values instead of positive values. This change fixes how unsigned integers are printed in the renderer.
=> Fix not rendering uint64_t values greater than the int64_t max value

README.md, include/inja/function_storage.hpp, include/inja/renderer.hpp, single_include/inja/inja.hpp, test/test-functions.cpp
Add capitalize function like jinja.
https://jinja.palletsprojects.com/en/3.1.x/templates/#jinja-filters.capitalize
=> Add capitalize function

.github/workflows/ci.yml, README.md, include/inja/config.hpp, include/inja/environment.hpp, include/inja/renderer.hpp, single_include/inja/inja.hpp
Since (j)inja templates are often used for creating HTML, it might be useful for inja to have a feature that does this. It is pretty inconvenient to manually have to escape all JSON strings. This PR adds a one stop set_html_autoescape feature that will HTML escape all strings for you. This is only available through an Environment.
=> Add HTML autoescape

CMakeLists.txt, include/inja/environment.hpp, include/inja/exceptions.hpp, include/inja/function_storage.hpp, include/inja/lexer.hpp, include/inja/node.hpp, include/inja/parser.hpp, include/inja/renderer.hpp, include/inja/statistics.hpp, include/inja/template.hpp, include/inja/utils.hpp, single_include/inja/inja.hpp, test/test-files.cpp, test/test-functions.cpp, test/test-renderer.cpp, test/test-units.cpp, test/test.cpp
The commit messages already describe it.
The first commit does minor fixes suggested by clang-tidy which includes changing the headers. There are still many recommendation left but would require too much change which the owner needs to decide.
The second commit adds an installation of the single header. The problem is that headers like `<inja/environment.hpp>` themselves cannot be included because headers are missing. The library only works when including `<inja/inja.hpp>` or the single header.
All tests pass.
The project structure is really odd in a way that it does not include dependencies as headers but assumes that they are resolved by headers that include them which breaks the source code when the original files like `<inja/environment.hpp>`  are included directly. I tried to solve …
=> clang-tidy applied and CMake installation of the single header added

include/inja/parser.hpp, include/inja/template.hpp, single_include/inja/inja.hpp
By taking the template content by value and moving into the local member, we can prevent and additional copy of 'content' when creating a Template.
=> Removes unnecessary template content copy

include/inja/parser.hpp, single_include/inja/inja.hpp
We need to resets current_block to a nullptr after parsing the template in `parse_into`, otherwise, current_block will refer to local stack space after we return from Parser::parse.
=> Prevent local stack memory leakage when parsing

include/inja/lexer.hpp, single_include/inja/inja.hpp, test/benchmark.cpp, test/test-files.cpp
- Add tok_start and pos initialization to Lexer constructor
- Fix clang-tidy uninitialized fields warning
```bash
inja/include/inja/parser.hpp:625:12: warning: 2 uninitialized fields at the end of the constructor call [clang-analyzer-optin.cplusplus.UninitializedObject]
625 |   explicit Parser(const ParserConfig& parser_config, const LexerConfig& lexer_config, TemplateStorage& template_storage,
|            ^
inja/include/inja/lexer.hpp:45:10: note: uninitialized field 'this->lexer.tok_start'
45 |   size_t tok_start;
|          ^~~~~~~~~
inja/include/inja/lexer.hpp:46:10: note: uninitialized field 'this->lexer.pos'
46 |   size_t pos;
```
=> Initialize missing fields in Lexer constructor

include/inja/renderer.hpp, single_include/inja/inja.hpp
Hi, thanks for this library, and adding HTML escaping in #292!
It'd be convenient if the `htmlescape` function was public for templates where HTML escaping is needed for some variables but not others.
```cpp
std::string escaped = inja::htmlescape("<h1></h1>");
```
Edit: Another idea would be to have a way to disable escaping for certain variables in templates (this would be a safer approach since it wouldn't require disabling autoescape).
=> Make `htmlescape` function public
